// flow-typed signature: 5f5bf3ea5b597fff203eca817b45a46c
// flow-typed version: <<STUB>>/flow-type_v^1.0.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-type/examples/ignored' {
  declare module.exports: any;
}

declare module 'flow-type/lib/cli' {
  declare module.exports: any;
}

declare module 'flow-type/lib/register' {
  declare module.exports: any;
}

declare module 'flow-type/lib/strip' {
  declare module.exports: any;
}

declare module 'flow-type/lib/walk' {
  declare module.exports: any;
}

declare module 'flow-type/register' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/def-site-variance/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/def-site-variance/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-array-types/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-array-types/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-call-properties/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-call-properties/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-declare-module/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-declare-module/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-declare-statements/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-declare-statements/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-directive/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-directive/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-interfaces-module-and-script/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-interfaces-module-and-script/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-qualified-generic-type/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-qualified-generic-type/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-string-literal-types/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-string-literal-types/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-tuples/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-tuples/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-type-alias/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-type-alias/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-type-annotations/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-type-annotations/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-typecasts/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/strip-typecasts/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/type-comments/actual' {
  declare module.exports: any;
}

declare module 'flow-type/test/fixtures/type-comments/expected' {
  declare module.exports: any;
}

declare module 'flow-type/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-type/examples/ignored.js' {
  declare module.exports: $Exports<'flow-type/examples/ignored'>;
}
declare module 'flow-type/lib/cli.js' {
  declare module.exports: $Exports<'flow-type/lib/cli'>;
}
declare module 'flow-type/lib/register.js' {
  declare module.exports: $Exports<'flow-type/lib/register'>;
}
declare module 'flow-type/lib/strip.js' {
  declare module.exports: $Exports<'flow-type/lib/strip'>;
}
declare module 'flow-type/lib/walk.js' {
  declare module.exports: $Exports<'flow-type/lib/walk'>;
}
declare module 'flow-type/register.js' {
  declare module.exports: $Exports<'flow-type/register'>;
}
declare module 'flow-type/test/fixtures/def-site-variance/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/def-site-variance/actual'>;
}
declare module 'flow-type/test/fixtures/def-site-variance/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/def-site-variance/expected'>;
}
declare module 'flow-type/test/fixtures/strip-array-types/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-array-types/actual'>;
}
declare module 'flow-type/test/fixtures/strip-array-types/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-array-types/expected'>;
}
declare module 'flow-type/test/fixtures/strip-call-properties/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-call-properties/actual'>;
}
declare module 'flow-type/test/fixtures/strip-call-properties/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-call-properties/expected'>;
}
declare module 'flow-type/test/fixtures/strip-declare-module/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-declare-module/actual'>;
}
declare module 'flow-type/test/fixtures/strip-declare-module/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-declare-module/expected'>;
}
declare module 'flow-type/test/fixtures/strip-declare-statements/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-declare-statements/actual'>;
}
declare module 'flow-type/test/fixtures/strip-declare-statements/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-declare-statements/expected'>;
}
declare module 'flow-type/test/fixtures/strip-directive/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-directive/actual'>;
}
declare module 'flow-type/test/fixtures/strip-directive/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-directive/expected'>;
}
declare module 'flow-type/test/fixtures/strip-interfaces-module-and-script/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-interfaces-module-and-script/actual'>;
}
declare module 'flow-type/test/fixtures/strip-interfaces-module-and-script/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-interfaces-module-and-script/expected'>;
}
declare module 'flow-type/test/fixtures/strip-qualified-generic-type/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-qualified-generic-type/actual'>;
}
declare module 'flow-type/test/fixtures/strip-qualified-generic-type/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-qualified-generic-type/expected'>;
}
declare module 'flow-type/test/fixtures/strip-string-literal-types/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-string-literal-types/actual'>;
}
declare module 'flow-type/test/fixtures/strip-string-literal-types/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-string-literal-types/expected'>;
}
declare module 'flow-type/test/fixtures/strip-tuples/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-tuples/actual'>;
}
declare module 'flow-type/test/fixtures/strip-tuples/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-tuples/expected'>;
}
declare module 'flow-type/test/fixtures/strip-type-alias/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-type-alias/actual'>;
}
declare module 'flow-type/test/fixtures/strip-type-alias/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-type-alias/expected'>;
}
declare module 'flow-type/test/fixtures/strip-type-annotations/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-type-annotations/actual'>;
}
declare module 'flow-type/test/fixtures/strip-type-annotations/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-type-annotations/expected'>;
}
declare module 'flow-type/test/fixtures/strip-typecasts/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-typecasts/actual'>;
}
declare module 'flow-type/test/fixtures/strip-typecasts/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/strip-typecasts/expected'>;
}
declare module 'flow-type/test/fixtures/type-comments/actual.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/type-comments/actual'>;
}
declare module 'flow-type/test/fixtures/type-comments/expected.js' {
  declare module.exports: $Exports<'flow-type/test/fixtures/type-comments/expected'>;
}
declare module 'flow-type/test/test.js' {
  declare module.exports: $Exports<'flow-type/test/test'>;
}
