// flow-typed signature: 76e535fa91a940c8989bf10ee4b37993
// flow-typed version: <<STUB>>/oidc-client_v^1.10.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oidc-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oidc-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oidc-client/dist/oidc-client' {
  declare module.exports: any;
}

declare module 'oidc-client/dist/oidc-client.min' {
  declare module.exports: any;
}

declare module 'oidc-client/dist/oidc-client.rsa256.slim' {
  declare module.exports: any;
}

declare module 'oidc-client/dist/oidc-client.rsa256.slim.min' {
  declare module.exports: any;
}

declare module 'oidc-client/dist/oidc-client.slim' {
  declare module.exports: any;
}

declare module 'oidc-client/dist/oidc-client.slim.min' {
  declare module.exports: any;
}

declare module 'oidc-client/gulpfile' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/dist/jsrsasign' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/base64-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/base64' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/aes_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/aes' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/cipher-core_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/cipher-core' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/enc-base64_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/enc-base64' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/hmac_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/hmac' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/md5_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/md5' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/pbkdf2_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/pbkdf2' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/ripemd160_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/ripemd160' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha1_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha1' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha224_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha224' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha256_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha256' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha384_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha384' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha512_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/sha512' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/tripledes_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/tripledes' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/x64-core_min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/cj/x64-core' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/ec-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/ec-patch-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/ec-patch' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/ec' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/jsbn-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/jsbn' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/jsbn2-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/jsbn2' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/json-sans-eval-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/json-sans-eval' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/prng4-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/prng4' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rng-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rng' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rsa-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rsa' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rsa2-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/rsa2' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/yahoo-min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/ext/yahoo' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/footer' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/header' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1cades-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1cms-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1csr-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1hex-1.1.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1ocsp-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1tsp-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/asn1x509-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/base64x-1.1.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/crypto-1.1.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/dsa-2.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/ecdsa-modified-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/ecparam-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/jws-3.3.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/jwsjs-2.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/keyutil-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/nodeutil-1.0.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/rsapem-1.1.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/rsasign-1.2.min' {
  declare module.exports: any;
}

declare module 'oidc-client/jsrsasign/min/x509-1.1.min' {
  declare module.exports: any;
}

declare module 'oidc-client/lib/oidc-client' {
  declare module.exports: any;
}

declare module 'oidc-client/lib/oidc-client.min' {
  declare module.exports: any;
}

declare module 'oidc-client/lib/oidc-client.rsa256' {
  declare module.exports: any;
}

declare module 'oidc-client/lib/oidc-client.rsa256.min' {
  declare module.exports: any;
}

declare module 'oidc-client/polyfills' {
  declare module.exports: any;
}

declare module 'oidc-client/src/AccessTokenEvents' {
  declare module.exports: any;
}

declare module 'oidc-client/src/CheckSessionIFrame' {
  declare module.exports: any;
}

declare module 'oidc-client/src/CordovaIFrameNavigator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/CordovaPopupNavigator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/CordovaPopupWindow' {
  declare module.exports: any;
}

declare module 'oidc-client/src/crypto/jsrsasign' {
  declare module.exports: any;
}

declare module 'oidc-client/src/crypto/rsa' {
  declare module.exports: any;
}

declare module 'oidc-client/src/ErrorResponse' {
  declare module.exports: any;
}

declare module 'oidc-client/src/Event' {
  declare module.exports: any;
}

declare module 'oidc-client/src/Global' {
  declare module.exports: any;
}

declare module 'oidc-client/src/IFrameNavigator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/IFrameWindow' {
  declare module.exports: any;
}

declare module 'oidc-client/src/InMemoryWebStorage' {
  declare module.exports: any;
}

declare module 'oidc-client/src/JoseUtil' {
  declare module.exports: any;
}

declare module 'oidc-client/src/JoseUtilImpl' {
  declare module.exports: any;
}

declare module 'oidc-client/src/JoseUtilRsa' {
  declare module.exports: any;
}

declare module 'oidc-client/src/JsonService' {
  declare module.exports: any;
}

declare module 'oidc-client/src/Log' {
  declare module.exports: any;
}

declare module 'oidc-client/src/MetadataService' {
  declare module.exports: any;
}

declare module 'oidc-client/src/OidcClient' {
  declare module.exports: any;
}

declare module 'oidc-client/src/OidcClientSettings' {
  declare module.exports: any;
}

declare module 'oidc-client/src/PopupNavigator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/PopupWindow' {
  declare module.exports: any;
}

declare module 'oidc-client/src/random' {
  declare module.exports: any;
}

declare module 'oidc-client/src/RedirectNavigator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/ResponseValidator' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SessionMonitor' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SigninRequest' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SigninResponse' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SigninState' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SignoutRequest' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SignoutResponse' {
  declare module.exports: any;
}

declare module 'oidc-client/src/SilentRenewService' {
  declare module.exports: any;
}

declare module 'oidc-client/src/State' {
  declare module.exports: any;
}

declare module 'oidc-client/src/Timer' {
  declare module.exports: any;
}

declare module 'oidc-client/src/TokenClient' {
  declare module.exports: any;
}

declare module 'oidc-client/src/TokenRevocationClient' {
  declare module.exports: any;
}

declare module 'oidc-client/src/UrlUtility' {
  declare module.exports: any;
}

declare module 'oidc-client/src/User' {
  declare module.exports: any;
}

declare module 'oidc-client/src/UserInfoService' {
  declare module.exports: any;
}

declare module 'oidc-client/src/UserManager' {
  declare module.exports: any;
}

declare module 'oidc-client/src/UserManagerEvents' {
  declare module.exports: any;
}

declare module 'oidc-client/src/UserManagerSettings' {
  declare module.exports: any;
}

declare module 'oidc-client/src/WebStorageStateStore' {
  declare module.exports: any;
}

declare module 'oidc-client/version' {
  declare module.exports: any;
}

declare module 'oidc-client/webpack.base' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oidc-client/dist/oidc-client.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client'>;
}
declare module 'oidc-client/dist/oidc-client.min.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client.min'>;
}
declare module 'oidc-client/dist/oidc-client.rsa256.slim.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client.rsa256.slim'>;
}
declare module 'oidc-client/dist/oidc-client.rsa256.slim.min.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client.rsa256.slim.min'>;
}
declare module 'oidc-client/dist/oidc-client.slim.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client.slim'>;
}
declare module 'oidc-client/dist/oidc-client.slim.min.js' {
  declare module.exports: $Exports<'oidc-client/dist/oidc-client.slim.min'>;
}
declare module 'oidc-client/gulpfile.js' {
  declare module.exports: $Exports<'oidc-client/gulpfile'>;
}
declare module 'oidc-client/index' {
  declare module.exports: $Exports<'oidc-client'>;
}
declare module 'oidc-client/index.js' {
  declare module.exports: $Exports<'oidc-client'>;
}
declare module 'oidc-client/jsrsasign/dist/jsrsasign.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/dist/jsrsasign'>;
}
declare module 'oidc-client/jsrsasign/ext/base64-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/base64-min'>;
}
declare module 'oidc-client/jsrsasign/ext/base64.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/base64'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/aes_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/aes_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/aes.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/aes'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/cipher-core_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/cipher-core_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/cipher-core.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/cipher-core'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix-min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/cryptojs-312-core-fix'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/enc-base64_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/enc-base64_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/enc-base64.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/enc-base64'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/hmac_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/hmac_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/hmac.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/hmac'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/md5_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/md5_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/md5.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/md5'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/pbkdf2_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/pbkdf2_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/pbkdf2.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/pbkdf2'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/ripemd160_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/ripemd160_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/ripemd160.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/ripemd160'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha1_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha1_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha1.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha1'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha224_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha224_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha224.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha224'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha256_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha256_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha256.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha256'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha384_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha384_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha384.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha384'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha512_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha512_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/sha512.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/sha512'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/tripledes_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/tripledes_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/tripledes.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/tripledes'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/x64-core_min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/x64-core_min'>;
}
declare module 'oidc-client/jsrsasign/ext/cj/x64-core.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/cj/x64-core'>;
}
declare module 'oidc-client/jsrsasign/ext/ec-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/ec-min'>;
}
declare module 'oidc-client/jsrsasign/ext/ec-patch-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/ec-patch-min'>;
}
declare module 'oidc-client/jsrsasign/ext/ec-patch.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/ec-patch'>;
}
declare module 'oidc-client/jsrsasign/ext/ec.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/ec'>;
}
declare module 'oidc-client/jsrsasign/ext/jsbn-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/jsbn-min'>;
}
declare module 'oidc-client/jsrsasign/ext/jsbn.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/jsbn'>;
}
declare module 'oidc-client/jsrsasign/ext/jsbn2-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/jsbn2-min'>;
}
declare module 'oidc-client/jsrsasign/ext/jsbn2.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/jsbn2'>;
}
declare module 'oidc-client/jsrsasign/ext/json-sans-eval-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/json-sans-eval-min'>;
}
declare module 'oidc-client/jsrsasign/ext/json-sans-eval.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/json-sans-eval'>;
}
declare module 'oidc-client/jsrsasign/ext/prng4-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/prng4-min'>;
}
declare module 'oidc-client/jsrsasign/ext/prng4.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/prng4'>;
}
declare module 'oidc-client/jsrsasign/ext/rng-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rng-min'>;
}
declare module 'oidc-client/jsrsasign/ext/rng.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rng'>;
}
declare module 'oidc-client/jsrsasign/ext/rsa-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rsa-min'>;
}
declare module 'oidc-client/jsrsasign/ext/rsa.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rsa'>;
}
declare module 'oidc-client/jsrsasign/ext/rsa2-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rsa2-min'>;
}
declare module 'oidc-client/jsrsasign/ext/rsa2.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/rsa2'>;
}
declare module 'oidc-client/jsrsasign/ext/yahoo-min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/yahoo-min'>;
}
declare module 'oidc-client/jsrsasign/ext/yahoo.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/ext/yahoo'>;
}
declare module 'oidc-client/jsrsasign/footer.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/footer'>;
}
declare module 'oidc-client/jsrsasign/header.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/header'>;
}
declare module 'oidc-client/jsrsasign/min/asn1-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1cades-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1cades-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1cms-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1cms-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1csr-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1csr-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1hex-1.1.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1hex-1.1.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1ocsp-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1ocsp-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1tsp-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1tsp-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/asn1x509-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/asn1x509-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/base64x-1.1.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/base64x-1.1.min'>;
}
declare module 'oidc-client/jsrsasign/min/crypto-1.1.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/crypto-1.1.min'>;
}
declare module 'oidc-client/jsrsasign/min/dsa-2.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/dsa-2.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/ecdsa-modified-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/ecdsa-modified-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/ecparam-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/ecparam-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/jws-3.3.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/jws-3.3.min'>;
}
declare module 'oidc-client/jsrsasign/min/jwsjs-2.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/jwsjs-2.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/keyutil-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/keyutil-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/nodeutil-1.0.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/nodeutil-1.0.min'>;
}
declare module 'oidc-client/jsrsasign/min/rsapem-1.1.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/rsapem-1.1.min'>;
}
declare module 'oidc-client/jsrsasign/min/rsasign-1.2.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/rsasign-1.2.min'>;
}
declare module 'oidc-client/jsrsasign/min/x509-1.1.min.js' {
  declare module.exports: $Exports<'oidc-client/jsrsasign/min/x509-1.1.min'>;
}
declare module 'oidc-client/lib/oidc-client.js' {
  declare module.exports: $Exports<'oidc-client/lib/oidc-client'>;
}
declare module 'oidc-client/lib/oidc-client.min.js' {
  declare module.exports: $Exports<'oidc-client/lib/oidc-client.min'>;
}
declare module 'oidc-client/lib/oidc-client.rsa256.js' {
  declare module.exports: $Exports<'oidc-client/lib/oidc-client.rsa256'>;
}
declare module 'oidc-client/lib/oidc-client.rsa256.min.js' {
  declare module.exports: $Exports<'oidc-client/lib/oidc-client.rsa256.min'>;
}
declare module 'oidc-client/polyfills.js' {
  declare module.exports: $Exports<'oidc-client/polyfills'>;
}
declare module 'oidc-client/src/AccessTokenEvents.js' {
  declare module.exports: $Exports<'oidc-client/src/AccessTokenEvents'>;
}
declare module 'oidc-client/src/CheckSessionIFrame.js' {
  declare module.exports: $Exports<'oidc-client/src/CheckSessionIFrame'>;
}
declare module 'oidc-client/src/CordovaIFrameNavigator.js' {
  declare module.exports: $Exports<'oidc-client/src/CordovaIFrameNavigator'>;
}
declare module 'oidc-client/src/CordovaPopupNavigator.js' {
  declare module.exports: $Exports<'oidc-client/src/CordovaPopupNavigator'>;
}
declare module 'oidc-client/src/CordovaPopupWindow.js' {
  declare module.exports: $Exports<'oidc-client/src/CordovaPopupWindow'>;
}
declare module 'oidc-client/src/crypto/jsrsasign.js' {
  declare module.exports: $Exports<'oidc-client/src/crypto/jsrsasign'>;
}
declare module 'oidc-client/src/crypto/rsa.js' {
  declare module.exports: $Exports<'oidc-client/src/crypto/rsa'>;
}
declare module 'oidc-client/src/ErrorResponse.js' {
  declare module.exports: $Exports<'oidc-client/src/ErrorResponse'>;
}
declare module 'oidc-client/src/Event.js' {
  declare module.exports: $Exports<'oidc-client/src/Event'>;
}
declare module 'oidc-client/src/Global.js' {
  declare module.exports: $Exports<'oidc-client/src/Global'>;
}
declare module 'oidc-client/src/IFrameNavigator.js' {
  declare module.exports: $Exports<'oidc-client/src/IFrameNavigator'>;
}
declare module 'oidc-client/src/IFrameWindow.js' {
  declare module.exports: $Exports<'oidc-client/src/IFrameWindow'>;
}
declare module 'oidc-client/src/InMemoryWebStorage.js' {
  declare module.exports: $Exports<'oidc-client/src/InMemoryWebStorage'>;
}
declare module 'oidc-client/src/JoseUtil.js' {
  declare module.exports: $Exports<'oidc-client/src/JoseUtil'>;
}
declare module 'oidc-client/src/JoseUtilImpl.js' {
  declare module.exports: $Exports<'oidc-client/src/JoseUtilImpl'>;
}
declare module 'oidc-client/src/JoseUtilRsa.js' {
  declare module.exports: $Exports<'oidc-client/src/JoseUtilRsa'>;
}
declare module 'oidc-client/src/JsonService.js' {
  declare module.exports: $Exports<'oidc-client/src/JsonService'>;
}
declare module 'oidc-client/src/Log.js' {
  declare module.exports: $Exports<'oidc-client/src/Log'>;
}
declare module 'oidc-client/src/MetadataService.js' {
  declare module.exports: $Exports<'oidc-client/src/MetadataService'>;
}
declare module 'oidc-client/src/OidcClient.js' {
  declare module.exports: $Exports<'oidc-client/src/OidcClient'>;
}
declare module 'oidc-client/src/OidcClientSettings.js' {
  declare module.exports: $Exports<'oidc-client/src/OidcClientSettings'>;
}
declare module 'oidc-client/src/PopupNavigator.js' {
  declare module.exports: $Exports<'oidc-client/src/PopupNavigator'>;
}
declare module 'oidc-client/src/PopupWindow.js' {
  declare module.exports: $Exports<'oidc-client/src/PopupWindow'>;
}
declare module 'oidc-client/src/random.js' {
  declare module.exports: $Exports<'oidc-client/src/random'>;
}
declare module 'oidc-client/src/RedirectNavigator.js' {
  declare module.exports: $Exports<'oidc-client/src/RedirectNavigator'>;
}
declare module 'oidc-client/src/ResponseValidator.js' {
  declare module.exports: $Exports<'oidc-client/src/ResponseValidator'>;
}
declare module 'oidc-client/src/SessionMonitor.js' {
  declare module.exports: $Exports<'oidc-client/src/SessionMonitor'>;
}
declare module 'oidc-client/src/SigninRequest.js' {
  declare module.exports: $Exports<'oidc-client/src/SigninRequest'>;
}
declare module 'oidc-client/src/SigninResponse.js' {
  declare module.exports: $Exports<'oidc-client/src/SigninResponse'>;
}
declare module 'oidc-client/src/SigninState.js' {
  declare module.exports: $Exports<'oidc-client/src/SigninState'>;
}
declare module 'oidc-client/src/SignoutRequest.js' {
  declare module.exports: $Exports<'oidc-client/src/SignoutRequest'>;
}
declare module 'oidc-client/src/SignoutResponse.js' {
  declare module.exports: $Exports<'oidc-client/src/SignoutResponse'>;
}
declare module 'oidc-client/src/SilentRenewService.js' {
  declare module.exports: $Exports<'oidc-client/src/SilentRenewService'>;
}
declare module 'oidc-client/src/State.js' {
  declare module.exports: $Exports<'oidc-client/src/State'>;
}
declare module 'oidc-client/src/Timer.js' {
  declare module.exports: $Exports<'oidc-client/src/Timer'>;
}
declare module 'oidc-client/src/TokenClient.js' {
  declare module.exports: $Exports<'oidc-client/src/TokenClient'>;
}
declare module 'oidc-client/src/TokenRevocationClient.js' {
  declare module.exports: $Exports<'oidc-client/src/TokenRevocationClient'>;
}
declare module 'oidc-client/src/UrlUtility.js' {
  declare module.exports: $Exports<'oidc-client/src/UrlUtility'>;
}
declare module 'oidc-client/src/User.js' {
  declare module.exports: $Exports<'oidc-client/src/User'>;
}
declare module 'oidc-client/src/UserInfoService.js' {
  declare module.exports: $Exports<'oidc-client/src/UserInfoService'>;
}
declare module 'oidc-client/src/UserManager.js' {
  declare module.exports: $Exports<'oidc-client/src/UserManager'>;
}
declare module 'oidc-client/src/UserManagerEvents.js' {
  declare module.exports: $Exports<'oidc-client/src/UserManagerEvents'>;
}
declare module 'oidc-client/src/UserManagerSettings.js' {
  declare module.exports: $Exports<'oidc-client/src/UserManagerSettings'>;
}
declare module 'oidc-client/src/WebStorageStateStore.js' {
  declare module.exports: $Exports<'oidc-client/src/WebStorageStateStore'>;
}
declare module 'oidc-client/version.js' {
  declare module.exports: $Exports<'oidc-client/version'>;
}
declare module 'oidc-client/webpack.base.js' {
  declare module.exports: $Exports<'oidc-client/webpack.base'>;
}
