// flow-typed signature: 23566ddbf776775e9e29a91bf9c06f68
// flow-typed version: <<STUB>>/react-debounce-input_v3.2.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-debounce-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-debounce-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-debounce-input/build/react-debounce-input' {
  declare module.exports: any;
}

declare module 'react-debounce-input/build/react-debounce-input.min' {
  declare module.exports: any;
}

declare module 'react-debounce-input/lib/Component' {
  declare module.exports: any;
}

declare module 'react-debounce-input/lib' {
  declare module.exports: any;
}

declare module 'react-debounce-input/src/Component' {
  declare module.exports: any;
}

declare module 'react-debounce-input/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-debounce-input/build/react-debounce-input.js' {
  declare module.exports: $Exports<'react-debounce-input/build/react-debounce-input'>;
}
declare module 'react-debounce-input/build/react-debounce-input.min.js' {
  declare module.exports: $Exports<'react-debounce-input/build/react-debounce-input.min'>;
}
declare module 'react-debounce-input/lib/Component.js' {
  declare module.exports: $Exports<'react-debounce-input/lib/Component'>;
}
declare module 'react-debounce-input/lib/index' {
  declare module.exports: $Exports<'react-debounce-input/lib'>;
}
declare module 'react-debounce-input/lib/index.js' {
  declare module.exports: $Exports<'react-debounce-input/lib'>;
}
declare module 'react-debounce-input/src/Component.js' {
  declare module.exports: $Exports<'react-debounce-input/src/Component'>;
}
declare module 'react-debounce-input/src/index' {
  declare module.exports: $Exports<'react-debounce-input/src'>;
}
declare module 'react-debounce-input/src/index.js' {
  declare module.exports: $Exports<'react-debounce-input/src'>;
}
