// flow-typed signature: 89936fa445470451dfe9103cffce1901
// flow-typed version: <<STUB>>/redux-oidc_v^4.0.0-beta1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-oidc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-oidc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-oidc/dist/redux-oidc' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/actions' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/CallbackComponent' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/constants' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/helpers/createUserManager' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/helpers/loadUser' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/helpers/processSilentRenew' {
  declare module.exports: any;
}

declare module 'redux-oidc/src' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/oidcMiddleware' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/OidcProvider' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/reducer/reducer-immutable' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/reducer/reducer' {
  declare module.exports: any;
}

declare module 'redux-oidc/src/SignoutCallbackComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-oidc/dist/redux-oidc.js' {
  declare module.exports: $Exports<'redux-oidc/dist/redux-oidc'>;
}
declare module 'redux-oidc/src/actions/index' {
  declare module.exports: $Exports<'redux-oidc/src/actions'>;
}
declare module 'redux-oidc/src/actions/index.js' {
  declare module.exports: $Exports<'redux-oidc/src/actions'>;
}
declare module 'redux-oidc/src/CallbackComponent.js' {
  declare module.exports: $Exports<'redux-oidc/src/CallbackComponent'>;
}
declare module 'redux-oidc/src/constants/index' {
  declare module.exports: $Exports<'redux-oidc/src/constants'>;
}
declare module 'redux-oidc/src/constants/index.js' {
  declare module.exports: $Exports<'redux-oidc/src/constants'>;
}
declare module 'redux-oidc/src/helpers/createUserManager.js' {
  declare module.exports: $Exports<'redux-oidc/src/helpers/createUserManager'>;
}
declare module 'redux-oidc/src/helpers/loadUser.js' {
  declare module.exports: $Exports<'redux-oidc/src/helpers/loadUser'>;
}
declare module 'redux-oidc/src/helpers/processSilentRenew.js' {
  declare module.exports: $Exports<'redux-oidc/src/helpers/processSilentRenew'>;
}
declare module 'redux-oidc/src/index' {
  declare module.exports: $Exports<'redux-oidc/src'>;
}
declare module 'redux-oidc/src/index.js' {
  declare module.exports: $Exports<'redux-oidc/src'>;
}
declare module 'redux-oidc/src/oidcMiddleware.js' {
  declare module.exports: $Exports<'redux-oidc/src/oidcMiddleware'>;
}
declare module 'redux-oidc/src/OidcProvider.js' {
  declare module.exports: $Exports<'redux-oidc/src/OidcProvider'>;
}
declare module 'redux-oidc/src/reducer/reducer-immutable.js' {
  declare module.exports: $Exports<'redux-oidc/src/reducer/reducer-immutable'>;
}
declare module 'redux-oidc/src/reducer/reducer.js' {
  declare module.exports: $Exports<'redux-oidc/src/reducer/reducer'>;
}
declare module 'redux-oidc/src/SignoutCallbackComponent.js' {
  declare module.exports: $Exports<'redux-oidc/src/SignoutCallbackComponent'>;
}
