// flow-typed signature: 30e5452a85010d53ed2c08e39cc825bc
// flow-typed version: <<STUB>>/swagger-client_v^3.10.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'swagger-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'swagger-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'swagger-client/dist/swagger-client.browser' {
  declare module.exports: any;
}

declare module 'swagger-client/dist/swagger-client.browser.min' {
  declare module.exports: any;
}

declare module 'swagger-client/es/commonjs' {
  declare module.exports: any;
}

declare module 'swagger-client/es/constants' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/oas3/build-request' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/oas3/content-serializer' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/oas3/parameter-builders' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/oas3/style-serializer' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/swagger2/build-request' {
  declare module.exports: any;
}

declare module 'swagger-client/es/execute/swagger2/parameter-builders' {
  declare module.exports: any;
}

declare module 'swagger-client/es/helpers' {
  declare module.exports: any;
}

declare module 'swagger-client/es/http' {
  declare module.exports: any;
}

declare module 'swagger-client/es' {
  declare module.exports: any;
}

declare module 'swagger-client/es/interfaces' {
  declare module.exports: any;
}

declare module 'swagger-client/es/internal/form-data-monkey-patch' {
  declare module.exports: any;
}

declare module 'swagger-client/es/resolver' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/helpers' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/all-of' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/context-tree' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/create-error' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/parameters' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/properties' {
  declare module.exports: any;
}

declare module 'swagger-client/es/specmap/lib/refs' {
  declare module.exports: any;
}

declare module 'swagger-client/es/subtree-resolver' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/commonjs' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/constants' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/oas3/build-request' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/oas3/content-serializer' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/oas3/parameter-builders' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/oas3/style-serializer' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/swagger2/build-request' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/execute/swagger2/parameter-builders' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/helpers' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/http' {
  declare module.exports: any;
}

declare module 'swagger-client/lib' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/interfaces' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/internal/form-data-monkey-patch' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/resolver' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/helpers' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/all-of' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/context-tree' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/create-error' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/parameters' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/properties' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/specmap/lib/refs' {
  declare module.exports: any;
}

declare module 'swagger-client/lib/subtree-resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'swagger-client/dist/swagger-client.browser.js' {
  declare module.exports: $Exports<'swagger-client/dist/swagger-client.browser'>;
}
declare module 'swagger-client/dist/swagger-client.browser.min.js' {
  declare module.exports: $Exports<'swagger-client/dist/swagger-client.browser.min'>;
}
declare module 'swagger-client/es/commonjs.js' {
  declare module.exports: $Exports<'swagger-client/es/commonjs'>;
}
declare module 'swagger-client/es/constants.js' {
  declare module.exports: $Exports<'swagger-client/es/constants'>;
}
declare module 'swagger-client/es/execute/index' {
  declare module.exports: $Exports<'swagger-client/es/execute'>;
}
declare module 'swagger-client/es/execute/index.js' {
  declare module.exports: $Exports<'swagger-client/es/execute'>;
}
declare module 'swagger-client/es/execute/oas3/build-request.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/oas3/build-request'>;
}
declare module 'swagger-client/es/execute/oas3/content-serializer.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/oas3/content-serializer'>;
}
declare module 'swagger-client/es/execute/oas3/parameter-builders.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/oas3/parameter-builders'>;
}
declare module 'swagger-client/es/execute/oas3/style-serializer.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/oas3/style-serializer'>;
}
declare module 'swagger-client/es/execute/swagger2/build-request.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/swagger2/build-request'>;
}
declare module 'swagger-client/es/execute/swagger2/parameter-builders.js' {
  declare module.exports: $Exports<'swagger-client/es/execute/swagger2/parameter-builders'>;
}
declare module 'swagger-client/es/helpers.js' {
  declare module.exports: $Exports<'swagger-client/es/helpers'>;
}
declare module 'swagger-client/es/http.js' {
  declare module.exports: $Exports<'swagger-client/es/http'>;
}
declare module 'swagger-client/es/index' {
  declare module.exports: $Exports<'swagger-client/es'>;
}
declare module 'swagger-client/es/index.js' {
  declare module.exports: $Exports<'swagger-client/es'>;
}
declare module 'swagger-client/es/interfaces.js' {
  declare module.exports: $Exports<'swagger-client/es/interfaces'>;
}
declare module 'swagger-client/es/internal/form-data-monkey-patch.js' {
  declare module.exports: $Exports<'swagger-client/es/internal/form-data-monkey-patch'>;
}
declare module 'swagger-client/es/resolver.js' {
  declare module.exports: $Exports<'swagger-client/es/resolver'>;
}
declare module 'swagger-client/es/specmap/helpers.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/helpers'>;
}
declare module 'swagger-client/es/specmap/index' {
  declare module.exports: $Exports<'swagger-client/es/specmap'>;
}
declare module 'swagger-client/es/specmap/index.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap'>;
}
declare module 'swagger-client/es/specmap/lib/all-of.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/all-of'>;
}
declare module 'swagger-client/es/specmap/lib/context-tree.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/context-tree'>;
}
declare module 'swagger-client/es/specmap/lib/create-error.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/create-error'>;
}
declare module 'swagger-client/es/specmap/lib/index' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib'>;
}
declare module 'swagger-client/es/specmap/lib/index.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib'>;
}
declare module 'swagger-client/es/specmap/lib/parameters.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/parameters'>;
}
declare module 'swagger-client/es/specmap/lib/properties.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/properties'>;
}
declare module 'swagger-client/es/specmap/lib/refs.js' {
  declare module.exports: $Exports<'swagger-client/es/specmap/lib/refs'>;
}
declare module 'swagger-client/es/subtree-resolver/index' {
  declare module.exports: $Exports<'swagger-client/es/subtree-resolver'>;
}
declare module 'swagger-client/es/subtree-resolver/index.js' {
  declare module.exports: $Exports<'swagger-client/es/subtree-resolver'>;
}
declare module 'swagger-client/lib/commonjs.js' {
  declare module.exports: $Exports<'swagger-client/lib/commonjs'>;
}
declare module 'swagger-client/lib/constants.js' {
  declare module.exports: $Exports<'swagger-client/lib/constants'>;
}
declare module 'swagger-client/lib/execute/index' {
  declare module.exports: $Exports<'swagger-client/lib/execute'>;
}
declare module 'swagger-client/lib/execute/index.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute'>;
}
declare module 'swagger-client/lib/execute/oas3/build-request.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/oas3/build-request'>;
}
declare module 'swagger-client/lib/execute/oas3/content-serializer.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/oas3/content-serializer'>;
}
declare module 'swagger-client/lib/execute/oas3/parameter-builders.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/oas3/parameter-builders'>;
}
declare module 'swagger-client/lib/execute/oas3/style-serializer.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/oas3/style-serializer'>;
}
declare module 'swagger-client/lib/execute/swagger2/build-request.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/swagger2/build-request'>;
}
declare module 'swagger-client/lib/execute/swagger2/parameter-builders.js' {
  declare module.exports: $Exports<'swagger-client/lib/execute/swagger2/parameter-builders'>;
}
declare module 'swagger-client/lib/helpers.js' {
  declare module.exports: $Exports<'swagger-client/lib/helpers'>;
}
declare module 'swagger-client/lib/http.js' {
  declare module.exports: $Exports<'swagger-client/lib/http'>;
}
declare module 'swagger-client/lib/index' {
  declare module.exports: $Exports<'swagger-client/lib'>;
}
declare module 'swagger-client/lib/index.js' {
  declare module.exports: $Exports<'swagger-client/lib'>;
}
declare module 'swagger-client/lib/interfaces.js' {
  declare module.exports: $Exports<'swagger-client/lib/interfaces'>;
}
declare module 'swagger-client/lib/internal/form-data-monkey-patch.js' {
  declare module.exports: $Exports<'swagger-client/lib/internal/form-data-monkey-patch'>;
}
declare module 'swagger-client/lib/resolver.js' {
  declare module.exports: $Exports<'swagger-client/lib/resolver'>;
}
declare module 'swagger-client/lib/specmap/helpers.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/helpers'>;
}
declare module 'swagger-client/lib/specmap/index' {
  declare module.exports: $Exports<'swagger-client/lib/specmap'>;
}
declare module 'swagger-client/lib/specmap/index.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap'>;
}
declare module 'swagger-client/lib/specmap/lib/all-of.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/all-of'>;
}
declare module 'swagger-client/lib/specmap/lib/context-tree.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/context-tree'>;
}
declare module 'swagger-client/lib/specmap/lib/create-error.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/create-error'>;
}
declare module 'swagger-client/lib/specmap/lib/index' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib'>;
}
declare module 'swagger-client/lib/specmap/lib/index.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib'>;
}
declare module 'swagger-client/lib/specmap/lib/parameters.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/parameters'>;
}
declare module 'swagger-client/lib/specmap/lib/properties.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/properties'>;
}
declare module 'swagger-client/lib/specmap/lib/refs.js' {
  declare module.exports: $Exports<'swagger-client/lib/specmap/lib/refs'>;
}
declare module 'swagger-client/lib/subtree-resolver/index' {
  declare module.exports: $Exports<'swagger-client/lib/subtree-resolver'>;
}
declare module 'swagger-client/lib/subtree-resolver/index.js' {
  declare module.exports: $Exports<'swagger-client/lib/subtree-resolver'>;
}
