// flow-typed signature: 266916a657868d27ee2efd316fe99830
// flow-typed version: <<STUB>>/vega-lite_v^4.0.0-beta.10/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-lite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-lite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-lite/build/src/aggregate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/axis' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/bin' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/channel' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/channeldef' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/config' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/encode' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/axis/properties' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/baseconcat' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/buildmodel' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/common' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/compile' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/concat' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/aggregate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/bin' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/calculate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/dataflow' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/debug' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/density' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/expressions' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/facet' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/filter' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/filterinvalid' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/flatten' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/fold' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/formatparse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/geojson' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/geopoint' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/graticule' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/identifier' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/impute' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/joinaggregate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/joinaggregatefacet' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/loess' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/lookup' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/optimize' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/optimizer' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/optimizers' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/pivot' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/quantile' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/regression' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/sample' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/sequence' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/source' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/stack' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/timeunit' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/data/window' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/facet' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/guide' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/header/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/header/common' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/header/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/header/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/layer' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/layoutsize/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/layoutsize/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/layoutsize/init' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/layoutsize/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/legend/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/legend/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/legend/encode' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/legend/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/legend/properties' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/area' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/bar' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/base' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/base' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/color' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/conditional' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/defined' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/nonposition' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/offset' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/position-align' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/position-point' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/position-range' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/position-rect' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/text' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/tooltip' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/encode/valueref' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/geoshape' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/image' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/init' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/line' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/mark' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/point' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/rect' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/rule' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/text' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/mark/tick' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/model' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/predicate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/projection/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/projection/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/projection/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/repeat' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/repeater' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/resolve' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/component' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/domain' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/properties' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/range' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/scale/type' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/assemble' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/interval' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/multi' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/parse' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/single' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/clear' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/inputs' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/legends' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/nearest' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/project' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/scales' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/toggle' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/transforms' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/translate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/selection/transforms/zoom' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/signal' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/split' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compile/unit' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark/base' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark/boxplot' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark/common' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark/errorband' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark/errorbar' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/compositemark' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/config' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/data' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/datetime' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/encoding' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/guide' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/header' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/impute' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/legend' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/log' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/log/message' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/logical' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/mark' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize/base' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize/core' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize/pathoverlay' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize/rangestep' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/normalize/ruleforrangedline' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/predicate' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/projection' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/resolve' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/scale' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/selection' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/signal' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/sort' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/base' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/concat' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/facet' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/layer' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/map' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/repeat' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/toplevel' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/spec/unit' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/stack' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/timeunit' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/title' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/transform' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/transformextract' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/type' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/util' {
  declare module.exports: any;
}

declare module 'vega-lite/build/src/vega.schema' {
  declare module.exports: any;
}

declare module 'vega-lite/build/vega-lite' {
  declare module.exports: any;
}

declare module 'vega-lite/build/vega-lite.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-lite/build/src/aggregate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/aggregate'>;
}
declare module 'vega-lite/build/src/axis.js' {
  declare module.exports: $Exports<'vega-lite/build/src/axis'>;
}
declare module 'vega-lite/build/src/bin.js' {
  declare module.exports: $Exports<'vega-lite/build/src/bin'>;
}
declare module 'vega-lite/build/src/channel.js' {
  declare module.exports: $Exports<'vega-lite/build/src/channel'>;
}
declare module 'vega-lite/build/src/channeldef.js' {
  declare module.exports: $Exports<'vega-lite/build/src/channeldef'>;
}
declare module 'vega-lite/build/src/compile/axis/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/assemble'>;
}
declare module 'vega-lite/build/src/compile/axis/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/component'>;
}
declare module 'vega-lite/build/src/compile/axis/config.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/config'>;
}
declare module 'vega-lite/build/src/compile/axis/encode.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/encode'>;
}
declare module 'vega-lite/build/src/compile/axis/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/parse'>;
}
declare module 'vega-lite/build/src/compile/axis/properties.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/axis/properties'>;
}
declare module 'vega-lite/build/src/compile/baseconcat.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/baseconcat'>;
}
declare module 'vega-lite/build/src/compile/buildmodel.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/buildmodel'>;
}
declare module 'vega-lite/build/src/compile/common.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/common'>;
}
declare module 'vega-lite/build/src/compile/compile.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/compile'>;
}
declare module 'vega-lite/build/src/compile/concat.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/concat'>;
}
declare module 'vega-lite/build/src/compile/data/aggregate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/aggregate'>;
}
declare module 'vega-lite/build/src/compile/data/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/assemble'>;
}
declare module 'vega-lite/build/src/compile/data/bin.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/bin'>;
}
declare module 'vega-lite/build/src/compile/data/calculate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/calculate'>;
}
declare module 'vega-lite/build/src/compile/data/dataflow.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/dataflow'>;
}
declare module 'vega-lite/build/src/compile/data/debug.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/debug'>;
}
declare module 'vega-lite/build/src/compile/data/density.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/density'>;
}
declare module 'vega-lite/build/src/compile/data/expressions.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/expressions'>;
}
declare module 'vega-lite/build/src/compile/data/facet.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/facet'>;
}
declare module 'vega-lite/build/src/compile/data/filter.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/filter'>;
}
declare module 'vega-lite/build/src/compile/data/filterinvalid.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/filterinvalid'>;
}
declare module 'vega-lite/build/src/compile/data/flatten.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/flatten'>;
}
declare module 'vega-lite/build/src/compile/data/fold.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/fold'>;
}
declare module 'vega-lite/build/src/compile/data/formatparse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/formatparse'>;
}
declare module 'vega-lite/build/src/compile/data/geojson.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/geojson'>;
}
declare module 'vega-lite/build/src/compile/data/geopoint.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/geopoint'>;
}
declare module 'vega-lite/build/src/compile/data/graticule.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/graticule'>;
}
declare module 'vega-lite/build/src/compile/data/identifier.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/identifier'>;
}
declare module 'vega-lite/build/src/compile/data/impute.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/impute'>;
}
declare module 'vega-lite/build/src/compile/data/index' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data'>;
}
declare module 'vega-lite/build/src/compile/data/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data'>;
}
declare module 'vega-lite/build/src/compile/data/joinaggregate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/joinaggregate'>;
}
declare module 'vega-lite/build/src/compile/data/joinaggregatefacet.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/joinaggregatefacet'>;
}
declare module 'vega-lite/build/src/compile/data/loess.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/loess'>;
}
declare module 'vega-lite/build/src/compile/data/lookup.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/lookup'>;
}
declare module 'vega-lite/build/src/compile/data/optimize.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/optimize'>;
}
declare module 'vega-lite/build/src/compile/data/optimizer.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/optimizer'>;
}
declare module 'vega-lite/build/src/compile/data/optimizers.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/optimizers'>;
}
declare module 'vega-lite/build/src/compile/data/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/parse'>;
}
declare module 'vega-lite/build/src/compile/data/pivot.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/pivot'>;
}
declare module 'vega-lite/build/src/compile/data/quantile.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/quantile'>;
}
declare module 'vega-lite/build/src/compile/data/regression.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/regression'>;
}
declare module 'vega-lite/build/src/compile/data/sample.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/sample'>;
}
declare module 'vega-lite/build/src/compile/data/sequence.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/sequence'>;
}
declare module 'vega-lite/build/src/compile/data/source.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/source'>;
}
declare module 'vega-lite/build/src/compile/data/stack.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/stack'>;
}
declare module 'vega-lite/build/src/compile/data/timeunit.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/timeunit'>;
}
declare module 'vega-lite/build/src/compile/data/window.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/data/window'>;
}
declare module 'vega-lite/build/src/compile/facet.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/facet'>;
}
declare module 'vega-lite/build/src/compile/guide.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/guide'>;
}
declare module 'vega-lite/build/src/compile/header/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/header/assemble'>;
}
declare module 'vega-lite/build/src/compile/header/common.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/header/common'>;
}
declare module 'vega-lite/build/src/compile/header/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/header/component'>;
}
declare module 'vega-lite/build/src/compile/header/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/header/parse'>;
}
declare module 'vega-lite/build/src/compile/layer.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/layer'>;
}
declare module 'vega-lite/build/src/compile/layoutsize/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/layoutsize/assemble'>;
}
declare module 'vega-lite/build/src/compile/layoutsize/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/layoutsize/component'>;
}
declare module 'vega-lite/build/src/compile/layoutsize/init.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/layoutsize/init'>;
}
declare module 'vega-lite/build/src/compile/layoutsize/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/layoutsize/parse'>;
}
declare module 'vega-lite/build/src/compile/legend/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/legend/assemble'>;
}
declare module 'vega-lite/build/src/compile/legend/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/legend/component'>;
}
declare module 'vega-lite/build/src/compile/legend/encode.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/legend/encode'>;
}
declare module 'vega-lite/build/src/compile/legend/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/legend/parse'>;
}
declare module 'vega-lite/build/src/compile/legend/properties.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/legend/properties'>;
}
declare module 'vega-lite/build/src/compile/mark/area.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/area'>;
}
declare module 'vega-lite/build/src/compile/mark/bar.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/bar'>;
}
declare module 'vega-lite/build/src/compile/mark/base.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/base'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/base.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/base'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/color.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/color'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/conditional.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/conditional'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/defined.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/defined'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/index' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/nonposition.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/nonposition'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/offset.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/offset'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/position-align.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/position-align'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/position-point.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/position-point'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/position-range.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/position-range'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/position-rect.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/position-rect'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/text.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/text'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/tooltip.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/tooltip'>;
}
declare module 'vega-lite/build/src/compile/mark/encode/valueref.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/encode/valueref'>;
}
declare module 'vega-lite/build/src/compile/mark/geoshape.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/geoshape'>;
}
declare module 'vega-lite/build/src/compile/mark/image.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/image'>;
}
declare module 'vega-lite/build/src/compile/mark/init.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/init'>;
}
declare module 'vega-lite/build/src/compile/mark/line.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/line'>;
}
declare module 'vega-lite/build/src/compile/mark/mark.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/mark'>;
}
declare module 'vega-lite/build/src/compile/mark/point.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/point'>;
}
declare module 'vega-lite/build/src/compile/mark/rect.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/rect'>;
}
declare module 'vega-lite/build/src/compile/mark/rule.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/rule'>;
}
declare module 'vega-lite/build/src/compile/mark/text.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/text'>;
}
declare module 'vega-lite/build/src/compile/mark/tick.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/mark/tick'>;
}
declare module 'vega-lite/build/src/compile/model.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/model'>;
}
declare module 'vega-lite/build/src/compile/predicate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/predicate'>;
}
declare module 'vega-lite/build/src/compile/projection/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/projection/assemble'>;
}
declare module 'vega-lite/build/src/compile/projection/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/projection/component'>;
}
declare module 'vega-lite/build/src/compile/projection/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/projection/parse'>;
}
declare module 'vega-lite/build/src/compile/repeat.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/repeat'>;
}
declare module 'vega-lite/build/src/compile/repeater.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/repeater'>;
}
declare module 'vega-lite/build/src/compile/resolve.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/resolve'>;
}
declare module 'vega-lite/build/src/compile/scale/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/assemble'>;
}
declare module 'vega-lite/build/src/compile/scale/component.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/component'>;
}
declare module 'vega-lite/build/src/compile/scale/domain.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/domain'>;
}
declare module 'vega-lite/build/src/compile/scale/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/parse'>;
}
declare module 'vega-lite/build/src/compile/scale/properties.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/properties'>;
}
declare module 'vega-lite/build/src/compile/scale/range.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/range'>;
}
declare module 'vega-lite/build/src/compile/scale/type.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/scale/type'>;
}
declare module 'vega-lite/build/src/compile/selection/assemble.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/assemble'>;
}
declare module 'vega-lite/build/src/compile/selection/index' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection'>;
}
declare module 'vega-lite/build/src/compile/selection/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection'>;
}
declare module 'vega-lite/build/src/compile/selection/interval.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/interval'>;
}
declare module 'vega-lite/build/src/compile/selection/multi.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/multi'>;
}
declare module 'vega-lite/build/src/compile/selection/parse.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/parse'>;
}
declare module 'vega-lite/build/src/compile/selection/single.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/single'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/clear.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/clear'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/inputs.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/inputs'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/legends.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/legends'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/nearest.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/nearest'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/project.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/project'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/scales.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/scales'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/toggle.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/toggle'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/transforms.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/transforms'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/translate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/translate'>;
}
declare module 'vega-lite/build/src/compile/selection/transforms/zoom.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/selection/transforms/zoom'>;
}
declare module 'vega-lite/build/src/compile/signal.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/signal'>;
}
declare module 'vega-lite/build/src/compile/split.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/split'>;
}
declare module 'vega-lite/build/src/compile/unit.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compile/unit'>;
}
declare module 'vega-lite/build/src/compositemark/base.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark/base'>;
}
declare module 'vega-lite/build/src/compositemark/boxplot.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark/boxplot'>;
}
declare module 'vega-lite/build/src/compositemark/common.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark/common'>;
}
declare module 'vega-lite/build/src/compositemark/errorband.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark/errorband'>;
}
declare module 'vega-lite/build/src/compositemark/errorbar.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark/errorbar'>;
}
declare module 'vega-lite/build/src/compositemark/index' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark'>;
}
declare module 'vega-lite/build/src/compositemark/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/compositemark'>;
}
declare module 'vega-lite/build/src/config.js' {
  declare module.exports: $Exports<'vega-lite/build/src/config'>;
}
declare module 'vega-lite/build/src/data.js' {
  declare module.exports: $Exports<'vega-lite/build/src/data'>;
}
declare module 'vega-lite/build/src/datetime.js' {
  declare module.exports: $Exports<'vega-lite/build/src/datetime'>;
}
declare module 'vega-lite/build/src/encoding.js' {
  declare module.exports: $Exports<'vega-lite/build/src/encoding'>;
}
declare module 'vega-lite/build/src/guide.js' {
  declare module.exports: $Exports<'vega-lite/build/src/guide'>;
}
declare module 'vega-lite/build/src/header.js' {
  declare module.exports: $Exports<'vega-lite/build/src/header'>;
}
declare module 'vega-lite/build/src/impute.js' {
  declare module.exports: $Exports<'vega-lite/build/src/impute'>;
}
declare module 'vega-lite/build/src/index' {
  declare module.exports: $Exports<'vega-lite/build/src'>;
}
declare module 'vega-lite/build/src/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src'>;
}
declare module 'vega-lite/build/src/legend.js' {
  declare module.exports: $Exports<'vega-lite/build/src/legend'>;
}
declare module 'vega-lite/build/src/log/index' {
  declare module.exports: $Exports<'vega-lite/build/src/log'>;
}
declare module 'vega-lite/build/src/log/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/log'>;
}
declare module 'vega-lite/build/src/log/message.js' {
  declare module.exports: $Exports<'vega-lite/build/src/log/message'>;
}
declare module 'vega-lite/build/src/logical.js' {
  declare module.exports: $Exports<'vega-lite/build/src/logical'>;
}
declare module 'vega-lite/build/src/mark.js' {
  declare module.exports: $Exports<'vega-lite/build/src/mark'>;
}
declare module 'vega-lite/build/src/normalize/base.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize/base'>;
}
declare module 'vega-lite/build/src/normalize/core.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize/core'>;
}
declare module 'vega-lite/build/src/normalize/index' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize'>;
}
declare module 'vega-lite/build/src/normalize/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize'>;
}
declare module 'vega-lite/build/src/normalize/pathoverlay.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize/pathoverlay'>;
}
declare module 'vega-lite/build/src/normalize/rangestep.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize/rangestep'>;
}
declare module 'vega-lite/build/src/normalize/ruleforrangedline.js' {
  declare module.exports: $Exports<'vega-lite/build/src/normalize/ruleforrangedline'>;
}
declare module 'vega-lite/build/src/predicate.js' {
  declare module.exports: $Exports<'vega-lite/build/src/predicate'>;
}
declare module 'vega-lite/build/src/projection.js' {
  declare module.exports: $Exports<'vega-lite/build/src/projection'>;
}
declare module 'vega-lite/build/src/resolve.js' {
  declare module.exports: $Exports<'vega-lite/build/src/resolve'>;
}
declare module 'vega-lite/build/src/scale.js' {
  declare module.exports: $Exports<'vega-lite/build/src/scale'>;
}
declare module 'vega-lite/build/src/selection.js' {
  declare module.exports: $Exports<'vega-lite/build/src/selection'>;
}
declare module 'vega-lite/build/src/signal.js' {
  declare module.exports: $Exports<'vega-lite/build/src/signal'>;
}
declare module 'vega-lite/build/src/sort.js' {
  declare module.exports: $Exports<'vega-lite/build/src/sort'>;
}
declare module 'vega-lite/build/src/spec/base.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/base'>;
}
declare module 'vega-lite/build/src/spec/concat.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/concat'>;
}
declare module 'vega-lite/build/src/spec/facet.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/facet'>;
}
declare module 'vega-lite/build/src/spec/index' {
  declare module.exports: $Exports<'vega-lite/build/src/spec'>;
}
declare module 'vega-lite/build/src/spec/index.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec'>;
}
declare module 'vega-lite/build/src/spec/layer.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/layer'>;
}
declare module 'vega-lite/build/src/spec/map.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/map'>;
}
declare module 'vega-lite/build/src/spec/repeat.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/repeat'>;
}
declare module 'vega-lite/build/src/spec/toplevel.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/toplevel'>;
}
declare module 'vega-lite/build/src/spec/unit.js' {
  declare module.exports: $Exports<'vega-lite/build/src/spec/unit'>;
}
declare module 'vega-lite/build/src/stack.js' {
  declare module.exports: $Exports<'vega-lite/build/src/stack'>;
}
declare module 'vega-lite/build/src/timeunit.js' {
  declare module.exports: $Exports<'vega-lite/build/src/timeunit'>;
}
declare module 'vega-lite/build/src/title.js' {
  declare module.exports: $Exports<'vega-lite/build/src/title'>;
}
declare module 'vega-lite/build/src/transform.js' {
  declare module.exports: $Exports<'vega-lite/build/src/transform'>;
}
declare module 'vega-lite/build/src/transformextract.js' {
  declare module.exports: $Exports<'vega-lite/build/src/transformextract'>;
}
declare module 'vega-lite/build/src/type.js' {
  declare module.exports: $Exports<'vega-lite/build/src/type'>;
}
declare module 'vega-lite/build/src/util.js' {
  declare module.exports: $Exports<'vega-lite/build/src/util'>;
}
declare module 'vega-lite/build/src/vega.schema.js' {
  declare module.exports: $Exports<'vega-lite/build/src/vega.schema'>;
}
declare module 'vega-lite/build/vega-lite.js' {
  declare module.exports: $Exports<'vega-lite/build/vega-lite'>;
}
declare module 'vega-lite/build/vega-lite.min.js' {
  declare module.exports: $Exports<'vega-lite/build/vega-lite.min'>;
}
