// flow-typed signature: 1b74ae1d3b0b1370792fe519d344618f
// flow-typed version: <<STUB>>/vega-embed_v^6.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vega-embed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vega-embed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vega-embed/build/src/container' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src/embed' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src/post' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src/style' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src/types' {
  declare module.exports: any;
}

declare module 'vega-embed/build/src/util' {
  declare module.exports: any;
}

declare module 'vega-embed/build/vega-embed' {
  declare module.exports: any;
}

declare module 'vega-embed/build/vega-embed.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vega-embed/build/src/container.js' {
  declare module.exports: $Exports<'vega-embed/build/src/container'>;
}
declare module 'vega-embed/build/src/embed.js' {
  declare module.exports: $Exports<'vega-embed/build/src/embed'>;
}
declare module 'vega-embed/build/src/index' {
  declare module.exports: $Exports<'vega-embed/build/src'>;
}
declare module 'vega-embed/build/src/index.js' {
  declare module.exports: $Exports<'vega-embed/build/src'>;
}
declare module 'vega-embed/build/src/post.js' {
  declare module.exports: $Exports<'vega-embed/build/src/post'>;
}
declare module 'vega-embed/build/src/style.js' {
  declare module.exports: $Exports<'vega-embed/build/src/style'>;
}
declare module 'vega-embed/build/src/types.js' {
  declare module.exports: $Exports<'vega-embed/build/src/types'>;
}
declare module 'vega-embed/build/src/util.js' {
  declare module.exports: $Exports<'vega-embed/build/src/util'>;
}
declare module 'vega-embed/build/vega-embed.js' {
  declare module.exports: $Exports<'vega-embed/build/vega-embed'>;
}
declare module 'vega-embed/build/vega-embed.min.js' {
  declare module.exports: $Exports<'vega-embed/build/vega-embed.min'>;
}
