server {
  listen       80;
  server_name  _;

  # send precompressed files with the ".gz" filename extension instead of regular files
  gzip_static on;

  client_max_body_size 0;

  root   /usr/share/nginx/html;
  index  index.html index.htm;

}
