server {
  listen       80;
  server_name  _;

  # send precompressed files with the ".gz" filename extension instead of regular files
  gzip_static on;

  client_max_body_size 0;

  root   /usr/share/nginx/html;
  index  index.html index.htm;

  location /data/ {
    rewrite ^/data/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

   location /data/.well-known/runtime-app-configuration {
        alias /usr/share/nginx/html/.well-known/runtime-app-configuration;
        default_type application/json;
    }

    location /data/.well-known/micro-app-configuration {
        alias /usr/share/nginx/html/.well-known/micro-app-configuration;
        default_type application/json;
    }
}
