// flow-typed signature: 33cc98277e8053affbfa224c0ff50355
// flow-typed version: <<STUB>>/@scality/core-ui_vgithub:scality/core-ui.git#add-dist-folder/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@scality/core-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@scality/core-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@scality/core-ui/__mocks__/fileMock' {
  declare module.exports: any;
}

declare module '@scality/core-ui/__mocks__/styleMock' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/areachart/AreaChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/banner/Banner.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/barchart/BarChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/breadcrumb/Breadcrumb.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/button/Button.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/checkbox/Checkbox.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/chips/Chips.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component.style' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/cloudprogressbar/CloudProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/collapsiblepanel/CollapsiblePanel.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/constants' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/dropdown/Dropdown.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/input/Input.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/input/Input.component.style' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/layout/Layout.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/linechart/LineChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/loader/Loader.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/modal/Modal.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/multiselect/MultiSelect.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/navbar/Navbar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/notifications/Notification.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/notifications/Notifications.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/progressbar/ProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/searchinput/SearchInput.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/select/Select.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/sidebar/Sidebar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/sparkline/SparkLine.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/steppers/Steppers.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/table/Table.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/tabs/Tabs.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/textarea/TextArea.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/toggle/Toggle.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/tooltip/Tooltip.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/components/vegachart/VegaChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/icons/branding' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/icons/scality-loading' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/style/theme' {
  declare module.exports: any;
}

declare module '@scality/core-ui/dist/utils' {
  declare module.exports: any;
}

declare module '@scality/core-ui/plopfile' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/areachart/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/areachart/AreaChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/areachart/AreaChart.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/banner/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/banner/Banner.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/banner/Banner.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/barchart/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/barchart/BarChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/barchart/BarChart.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/breadcrumb/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/button/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/button/Button.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/button/Button.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/checkbox/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/checkbox/Checkbox.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/checkbox/Checkbox.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/chips/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/chips/Chips.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/chips/Chips.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/circularprogressbar/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.style' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/cloudprogressbar/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/collapsiblepanel/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/constants' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/dropdown/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/dropdown/Dropdown.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/dropdown/Dropdown.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/input/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/input/Input.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/input/Input.component.style' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/input/Input.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/layout/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/layout/Layout.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/layout/Layout.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/linechart/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/linechart/LineChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/linechart/LineChart.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/loader/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/loader/Loader.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/loader/Loader.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/modal/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/modal/Modal.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/modal/Modal.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/multiselect/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/multiselect/MultiSelect.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/multiselect/MultiSelect.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/navbar/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/navbar/Navbar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/navbar/Navbar.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/notifications/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/notifications/Notification.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/notifications/Notifications.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/notifications/Notifications.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/progressbar/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/progressbar/ProgressBar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/progressbar/ProgressBar.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/searchinput/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/searchinput/SearchInput.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/searchinput/SearchInput.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/select/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/select/Select.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/select/Select.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sidebar/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sidebar/Sidebar.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sidebar/Sidebar.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sparkline/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sparkline/SparkLine.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/sparkline/SparkLine.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/steppers/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/steppers/Steppers.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/steppers/Steppers.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/table/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/table/Table.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/table/Table.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tabs/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tabs/Tabs.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tabs/Tabs.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/textarea/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/textarea/TextArea.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/textarea/TextArea.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/toggle/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/toggle/Toggle.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/toggle/Toggle.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tooltip/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tooltip/Tooltip.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/tooltip/Tooltip.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/vegachart/__snapshots__/config' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/vegachart/VegaChart.component' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/components/vegachart/VegaChart.component.test' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/icons/branding' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/icons/scality-loading' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/style/theme' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/lib/utils' {
  declare module.exports: any;
}

declare module '@scality/core-ui/src/setupTests' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/areachart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/banner' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/barchart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/breadcrumb' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/button' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/checkbox' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/chips' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/circularprogressbar' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/cloudprogressbar' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/collapsiblepanel' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/color' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/common' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/data/areachart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/data/barchart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/data/linechart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/data/list' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/data/sparklinechart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/dropdown' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/input' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/layout' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/linechart' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/loader' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/modal' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/multiselect' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/navbar' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/notifications' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/progressbar' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/searchinput' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/select' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/sidebar' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/sparkline' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/steppers' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/table' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/tabs' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/textarea' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/toggle' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/tooltip' {
  declare module.exports: any;
}

declare module '@scality/core-ui/stories/vegachart' {
  declare module.exports: any;
}

// Filename aliases
declare module '@scality/core-ui/__mocks__/fileMock.js' {
  declare module.exports: $Exports<'@scality/core-ui/__mocks__/fileMock'>;
}
declare module '@scality/core-ui/__mocks__/styleMock.js' {
  declare module.exports: $Exports<'@scality/core-ui/__mocks__/styleMock'>;
}
declare module '@scality/core-ui/dist/components/areachart/AreaChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/areachart/AreaChart.component'>;
}
declare module '@scality/core-ui/dist/components/banner/Banner.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/banner/Banner.component'>;
}
declare module '@scality/core-ui/dist/components/barchart/BarChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/barchart/BarChart.component'>;
}
declare module '@scality/core-ui/dist/components/breadcrumb/Breadcrumb.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/breadcrumb/Breadcrumb.component'>;
}
declare module '@scality/core-ui/dist/components/button/Button.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/button/Button.component'>;
}
declare module '@scality/core-ui/dist/components/checkbox/Checkbox.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/checkbox/Checkbox.component'>;
}
declare module '@scality/core-ui/dist/components/chips/Chips.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/chips/Chips.component'>;
}
declare module '@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component'>;
}
declare module '@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component.style.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/circularprogressbar/CircularProgressBar.component.style'>;
}
declare module '@scality/core-ui/dist/components/cloudprogressbar/CloudProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/cloudprogressbar/CloudProgressBar.component'>;
}
declare module '@scality/core-ui/dist/components/collapsiblepanel/CollapsiblePanel.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/collapsiblepanel/CollapsiblePanel.component'>;
}
declare module '@scality/core-ui/dist/components/constants.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/constants'>;
}
declare module '@scality/core-ui/dist/components/dropdown/Dropdown.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/dropdown/Dropdown.component'>;
}
declare module '@scality/core-ui/dist/components/input/Input.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/input/Input.component'>;
}
declare module '@scality/core-ui/dist/components/input/Input.component.style.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/input/Input.component.style'>;
}
declare module '@scality/core-ui/dist/components/layout/Layout.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/layout/Layout.component'>;
}
declare module '@scality/core-ui/dist/components/linechart/LineChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/linechart/LineChart.component'>;
}
declare module '@scality/core-ui/dist/components/loader/Loader.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/loader/Loader.component'>;
}
declare module '@scality/core-ui/dist/components/modal/Modal.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/modal/Modal.component'>;
}
declare module '@scality/core-ui/dist/components/multiselect/MultiSelect.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/multiselect/MultiSelect.component'>;
}
declare module '@scality/core-ui/dist/components/navbar/Navbar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/navbar/Navbar.component'>;
}
declare module '@scality/core-ui/dist/components/notifications/Notification.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/notifications/Notification.component'>;
}
declare module '@scality/core-ui/dist/components/notifications/Notifications.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/notifications/Notifications.component'>;
}
declare module '@scality/core-ui/dist/components/progressbar/ProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/progressbar/ProgressBar.component'>;
}
declare module '@scality/core-ui/dist/components/searchinput/SearchInput.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/searchinput/SearchInput.component'>;
}
declare module '@scality/core-ui/dist/components/select/Select.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/select/Select.component'>;
}
declare module '@scality/core-ui/dist/components/sidebar/Sidebar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/sidebar/Sidebar.component'>;
}
declare module '@scality/core-ui/dist/components/sparkline/SparkLine.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/sparkline/SparkLine.component'>;
}
declare module '@scality/core-ui/dist/components/steppers/Steppers.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/steppers/Steppers.component'>;
}
declare module '@scality/core-ui/dist/components/table/Table.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/table/Table.component'>;
}
declare module '@scality/core-ui/dist/components/tabs/Tabs.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/tabs/Tabs.component'>;
}
declare module '@scality/core-ui/dist/components/textarea/TextArea.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/textarea/TextArea.component'>;
}
declare module '@scality/core-ui/dist/components/toggle/Toggle.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/toggle/Toggle.component'>;
}
declare module '@scality/core-ui/dist/components/tooltip/Tooltip.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/tooltip/Tooltip.component'>;
}
declare module '@scality/core-ui/dist/components/vegachart/VegaChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/components/vegachart/VegaChart.component'>;
}
declare module '@scality/core-ui/dist/icons/branding.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/icons/branding'>;
}
declare module '@scality/core-ui/dist/icons/scality-loading.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/icons/scality-loading'>;
}
declare module '@scality/core-ui/dist/index' {
  declare module.exports: $Exports<'@scality/core-ui/dist'>;
}
declare module '@scality/core-ui/dist/index.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist'>;
}
declare module '@scality/core-ui/dist/style/theme.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/style/theme'>;
}
declare module '@scality/core-ui/dist/utils.js' {
  declare module.exports: $Exports<'@scality/core-ui/dist/utils'>;
}
declare module '@scality/core-ui/plopfile.js' {
  declare module.exports: $Exports<'@scality/core-ui/plopfile'>;
}
declare module '@scality/core-ui/src/lib/components/areachart/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/areachart/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/areachart/AreaChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/areachart/AreaChart.component'>;
}
declare module '@scality/core-ui/src/lib/components/areachart/AreaChart.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/areachart/AreaChart.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/banner/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/banner/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/banner/Banner.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/banner/Banner.component'>;
}
declare module '@scality/core-ui/src/lib/components/banner/Banner.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/banner/Banner.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/barchart/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/barchart/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/barchart/BarChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/barchart/BarChart.component'>;
}
declare module '@scality/core-ui/src/lib/components/barchart/BarChart.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/barchart/BarChart.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/breadcrumb/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/breadcrumb/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component'>;
}
declare module '@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/breadcrumb/Breadcrumb.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/button/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/button/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/button/Button.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/button/Button.component'>;
}
declare module '@scality/core-ui/src/lib/components/button/Button.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/button/Button.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/checkbox/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/checkbox/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/checkbox/Checkbox.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/checkbox/Checkbox.component'>;
}
declare module '@scality/core-ui/src/lib/components/checkbox/Checkbox.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/checkbox/Checkbox.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/chips/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/chips/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/chips/Chips.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/chips/Chips.component'>;
}
declare module '@scality/core-ui/src/lib/components/chips/Chips.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/chips/Chips.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/circularprogressbar/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/circularprogressbar/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component'>;
}
declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.style.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.style'>;
}
declare module '@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/circularprogressbar/CircularProgressBar.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/cloudprogressbar/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/cloudprogressbar/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component'>;
}
declare module '@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/cloudprogressbar/CloudProgressBar.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/collapsiblepanel/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/collapsiblepanel/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component'>;
}
declare module '@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/collapsiblepanel/CollapsiblePanel.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/constants.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/constants'>;
}
declare module '@scality/core-ui/src/lib/components/dropdown/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/dropdown/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/dropdown/Dropdown.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/dropdown/Dropdown.component'>;
}
declare module '@scality/core-ui/src/lib/components/dropdown/Dropdown.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/dropdown/Dropdown.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/input/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/input/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/input/Input.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/input/Input.component'>;
}
declare module '@scality/core-ui/src/lib/components/input/Input.component.style.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/input/Input.component.style'>;
}
declare module '@scality/core-ui/src/lib/components/input/Input.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/input/Input.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/layout/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/layout/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/layout/Layout.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/layout/Layout.component'>;
}
declare module '@scality/core-ui/src/lib/components/layout/Layout.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/layout/Layout.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/linechart/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/linechart/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/linechart/LineChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/linechart/LineChart.component'>;
}
declare module '@scality/core-ui/src/lib/components/linechart/LineChart.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/linechart/LineChart.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/loader/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/loader/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/loader/Loader.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/loader/Loader.component'>;
}
declare module '@scality/core-ui/src/lib/components/loader/Loader.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/loader/Loader.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/modal/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/modal/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/modal/Modal.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/modal/Modal.component'>;
}
declare module '@scality/core-ui/src/lib/components/modal/Modal.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/modal/Modal.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/multiselect/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/multiselect/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/multiselect/MultiSelect.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/multiselect/MultiSelect.component'>;
}
declare module '@scality/core-ui/src/lib/components/multiselect/MultiSelect.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/multiselect/MultiSelect.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/navbar/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/navbar/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/navbar/Navbar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/navbar/Navbar.component'>;
}
declare module '@scality/core-ui/src/lib/components/navbar/Navbar.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/navbar/Navbar.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/notifications/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/notifications/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/notifications/Notification.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/notifications/Notification.component'>;
}
declare module '@scality/core-ui/src/lib/components/notifications/Notifications.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/notifications/Notifications.component'>;
}
declare module '@scality/core-ui/src/lib/components/notifications/Notifications.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/notifications/Notifications.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/progressbar/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/progressbar/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/progressbar/ProgressBar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/progressbar/ProgressBar.component'>;
}
declare module '@scality/core-ui/src/lib/components/progressbar/ProgressBar.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/progressbar/ProgressBar.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/searchinput/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/searchinput/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/searchinput/SearchInput.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/searchinput/SearchInput.component'>;
}
declare module '@scality/core-ui/src/lib/components/searchinput/SearchInput.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/searchinput/SearchInput.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/select/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/select/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/select/Select.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/select/Select.component'>;
}
declare module '@scality/core-ui/src/lib/components/select/Select.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/select/Select.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/sidebar/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sidebar/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/sidebar/Sidebar.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sidebar/Sidebar.component'>;
}
declare module '@scality/core-ui/src/lib/components/sidebar/Sidebar.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sidebar/Sidebar.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/sparkline/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sparkline/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/sparkline/SparkLine.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sparkline/SparkLine.component'>;
}
declare module '@scality/core-ui/src/lib/components/sparkline/SparkLine.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/sparkline/SparkLine.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/steppers/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/steppers/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/steppers/Steppers.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/steppers/Steppers.component'>;
}
declare module '@scality/core-ui/src/lib/components/steppers/Steppers.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/steppers/Steppers.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/table/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/table/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/table/Table.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/table/Table.component'>;
}
declare module '@scality/core-ui/src/lib/components/table/Table.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/table/Table.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/tabs/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tabs/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/tabs/Tabs.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tabs/Tabs.component'>;
}
declare module '@scality/core-ui/src/lib/components/tabs/Tabs.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tabs/Tabs.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/textarea/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/textarea/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/textarea/TextArea.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/textarea/TextArea.component'>;
}
declare module '@scality/core-ui/src/lib/components/textarea/TextArea.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/textarea/TextArea.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/toggle/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/toggle/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/toggle/Toggle.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/toggle/Toggle.component'>;
}
declare module '@scality/core-ui/src/lib/components/toggle/Toggle.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/toggle/Toggle.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/tooltip/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tooltip/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/tooltip/Tooltip.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tooltip/Tooltip.component'>;
}
declare module '@scality/core-ui/src/lib/components/tooltip/Tooltip.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/tooltip/Tooltip.component.test'>;
}
declare module '@scality/core-ui/src/lib/components/vegachart/__snapshots__/config.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/vegachart/__snapshots__/config'>;
}
declare module '@scality/core-ui/src/lib/components/vegachart/VegaChart.component.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/vegachart/VegaChart.component'>;
}
declare module '@scality/core-ui/src/lib/components/vegachart/VegaChart.component.test.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/components/vegachart/VegaChart.component.test'>;
}
declare module '@scality/core-ui/src/lib/icons/branding.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/icons/branding'>;
}
declare module '@scality/core-ui/src/lib/icons/scality-loading.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/icons/scality-loading'>;
}
declare module '@scality/core-ui/src/lib/index' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib'>;
}
declare module '@scality/core-ui/src/lib/index.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib'>;
}
declare module '@scality/core-ui/src/lib/style/theme.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/style/theme'>;
}
declare module '@scality/core-ui/src/lib/utils.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/lib/utils'>;
}
declare module '@scality/core-ui/src/setupTests.js' {
  declare module.exports: $Exports<'@scality/core-ui/src/setupTests'>;
}
declare module '@scality/core-ui/stories/areachart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/areachart'>;
}
declare module '@scality/core-ui/stories/banner.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/banner'>;
}
declare module '@scality/core-ui/stories/barchart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/barchart'>;
}
declare module '@scality/core-ui/stories/breadcrumb.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/breadcrumb'>;
}
declare module '@scality/core-ui/stories/button.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/button'>;
}
declare module '@scality/core-ui/stories/checkbox.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/checkbox'>;
}
declare module '@scality/core-ui/stories/chips.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/chips'>;
}
declare module '@scality/core-ui/stories/circularprogressbar.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/circularprogressbar'>;
}
declare module '@scality/core-ui/stories/cloudprogressbar.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/cloudprogressbar'>;
}
declare module '@scality/core-ui/stories/collapsiblepanel.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/collapsiblepanel'>;
}
declare module '@scality/core-ui/stories/color.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/color'>;
}
declare module '@scality/core-ui/stories/common.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/common'>;
}
declare module '@scality/core-ui/stories/data/areachart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/data/areachart'>;
}
declare module '@scality/core-ui/stories/data/barchart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/data/barchart'>;
}
declare module '@scality/core-ui/stories/data/linechart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/data/linechart'>;
}
declare module '@scality/core-ui/stories/data/list.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/data/list'>;
}
declare module '@scality/core-ui/stories/data/sparklinechart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/data/sparklinechart'>;
}
declare module '@scality/core-ui/stories/dropdown.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/dropdown'>;
}
declare module '@scality/core-ui/stories/index' {
  declare module.exports: $Exports<'@scality/core-ui/stories'>;
}
declare module '@scality/core-ui/stories/index.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories'>;
}
declare module '@scality/core-ui/stories/input.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/input'>;
}
declare module '@scality/core-ui/stories/layout.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/layout'>;
}
declare module '@scality/core-ui/stories/linechart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/linechart'>;
}
declare module '@scality/core-ui/stories/loader.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/loader'>;
}
declare module '@scality/core-ui/stories/modal.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/modal'>;
}
declare module '@scality/core-ui/stories/multiselect.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/multiselect'>;
}
declare module '@scality/core-ui/stories/navbar.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/navbar'>;
}
declare module '@scality/core-ui/stories/notifications.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/notifications'>;
}
declare module '@scality/core-ui/stories/progressbar.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/progressbar'>;
}
declare module '@scality/core-ui/stories/searchinput.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/searchinput'>;
}
declare module '@scality/core-ui/stories/select.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/select'>;
}
declare module '@scality/core-ui/stories/sidebar.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/sidebar'>;
}
declare module '@scality/core-ui/stories/sparkline.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/sparkline'>;
}
declare module '@scality/core-ui/stories/steppers.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/steppers'>;
}
declare module '@scality/core-ui/stories/table.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/table'>;
}
declare module '@scality/core-ui/stories/tabs.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/tabs'>;
}
declare module '@scality/core-ui/stories/textarea.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/textarea'>;
}
declare module '@scality/core-ui/stories/toggle.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/toggle'>;
}
declare module '@scality/core-ui/stories/tooltip.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/tooltip'>;
}
declare module '@scality/core-ui/stories/vegachart.js' {
  declare module.exports: $Exports<'@scality/core-ui/stories/vegachart'>;
}
