---
name: release

on:
  release:
    types: [published]

jobs:
  retag-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: registry.scality.com
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Retag the docker image
        run: |
          docker pull registry.scality.com/zenko-ui-dev/zenko-ui:$GITHUB_SHA
          docker tag registry.scality.com/zenko-ui-dev/zenko-ui:$GITHUB_SHA registry.scality.com/zenko-ui/zenko-ui:$GITHUB_REF_NAME
          docker push registry.scality.com/zenko-ui/zenko-ui:$GITHUB_REF_NAME
