---
name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          ref: ${{ inputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: registry.scality.com
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependencies
        run: npm config set unsafe-perm true && npm ci

      - name: build assets
        run: npm run build

      - name: Build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: "registry.scality.com/zenko-ui/zenko-ui:${{ github.event.inputs.tag }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.13
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
