---
name: release

on:
  release:
    types: [published]
env:
  DEV_NAMESPACE: 'zenko-ui-dev'
  PROD_NAMESPACE: 'zenko-ui'
  REGISTRY: 'registry.scality.com'
  CONFIG_IMAGE: 'zenko-ui-config'
  UI_IMAGE: 'zenko-ui'

jobs:
  retag-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Retag the docker image
        run: |
          docker pull ${REGISTRY}/${DEV_NAMESPACE}/${UI_IMAGE}:$GITHUB_SHA
          docker pull ${REGISTRY}/${DEV_NAMESPACE}/${CONFIG_IMAGE}:$GITHUB_SHA
          docker tag ${REGISTRY}/${DEV_NAMESPACE}/${UI_IMAGE}:$GITHUB_SHA ${REGISTRY}/${PROD_NAMESPACE}/${UI_IMAGE}:$GITHUB_REF_NAME
          docker tag ${REGISTRY}/${DEV_NAMESPACE}/${CONFIG_IMAGE}:$GITHUB_SHA ${REGISTRY}/${PROD_NAMESPACE}/${CONFIG_IMAGE}:$GITHUB_REF_NAME
          docker push ${REGISTRY}/${PROD_NAMESPACE}/${UI_IMAGE}:$GITHUB_REF_NAME
          docker push ${REGISTRY}/${PROD_NAMESPACE}/${CONFIG_IMAGE}:$GITHUB_REF_NAME
